[features]
seeds = false
skip-lint = false
[programs.localnet]
tutorverse_contract = "7Dco5qTKFzHWKTnZoG93n73DEroWAcLxPJ1g8RiFaXLX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["./tutorverse-anchor/programs/tutorverse-contract"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tutorverse-anchor/tests/**/*.ts"
