FROM rust:slim-bookworm AS builder

# Add wasm target
RUN rustup target add wasm32-unknown-unknown

# Install wasm-pack for testing
RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

# Install trunk
ADD https://github.com/thedodd/trunk/releases/download/v0.17.5/trunk-x86_64-unknown-linux-gnu.tar.gz ./tmp
RUN cd /tmp && tar xf trunk-x86_64-unknown-linux-gnu.tar.gz && chmod +x trunk && mv trunk /bin

WORKDIR /usr/src/app

# build project without source code

# copy workspace files
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock

# copy anchor structure 
RUN mkdir tutorverse-anchor
# anchor contract
RUN mkdir -p  tutorverse-anchor/programs/tutorverse-contract/src
COPY tutorverse-anchor/programs/tutorverse-contract/Cargo.toml tutorverse-anchor/programs/tutorverse-contract/Cargo.toml
RUN touch tutorverse-anchor/programs/tutorverse-contract/src/lib.rs

# anchor-wasm
RUN mkdir -p tutorverse-anchor/anchor-wasm/src
COPY tutorverse-anchor/anchor-wasm/Cargo.toml ./tutorverse-anchor/anchor-wasm/Cargo.toml
RUN touch tutorverse-anchor/anchor-wasm/src/lib.rs

# frontend
RUN mkdir -p tutorverse-frontend/src
COPY tutorverse-frontend/Cargo.toml ./tutorverse-frontend/Cargo.toml
RUN touch tutorverse-frontend/index.html
RUN touch tutorverse-frontend/src/main.rs
RUN echo "fn main() {}" > tutorverse-frontend/src/main.rs

WORKDIR /usr/src/app/tutorverse-frontend
RUN trunk build --release

WORKDIR /usr/src/app

# remove template files
RUN rm -r tutorverse-frontend
RUN rm -r tutorverse-anchor

# build bin & libs
RUN rm ./target/wasm32-unknown-unknown/release/deps/tutorverse_frontend*
RUN rm ./target/wasm32-unknown-unknown/release/deps/libtutorverse_contract*
RUN rm ./target/release/deps/libanchor_wasm*

# copy over source code and deps
COPY tutorverse-anchor tutorverse-anchor
COPY tutorverse-frontend tutorverse-frontend

WORKDIR /usr/src/app/tutorverse-frontend
RUN trunk build --release

FROM nginx:alpine as runner

COPY --from=builder /usr/src/app/tutorverse-frontend/dist /usr/share/nginx/html
COPY ./tutorverse-frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]